### ISSUE TITLE
auto update submodules?

### ISSUE THREAD

**Issue by obtitus** [POI-Importer/POI-Importer.github.io#11]
I have an automated-script to keep https://github.com/POI-Importer/norge-barnehagefakta up-to-date. Could you either create a script that updates the sub-modules on a regular basis (say weekly or monthly), or link directly to the dataset by:

modifyign datasets.js to
`"url": "https://raw.githubusercontent.com/POI-Importer/norge-barnehagefakta/master/"`

As it stand, it could be chaotic if people start importing outdated metadata into openstreetmap.

**Comment by sanderd17** [comment]
I currently have no time to work on this anymore. I guess you could take over the project if you're interested.

**Comment by obtitus** [comment]
Ok, could you give me write access?
