### ISSUE TITLE
New dataset - fire hydrants in Davao City, Philippines

### ISSUE THREAD

**Issue by govvin** [POI-Importer/POI-Importer.github.io#14]
I am hoping that we could use this tool for our upcoming [Mapa-thon](https://ti.to/mapamore/kadayawan2017) where we hope to map the fire-fighting and emergency facilities in Davao City, Philippines.

[Here](https://gist.github.com/govvin/b1d66a5729efa2b48e23bcfe8db064b4) is the geojson file we intend to use.

Kindly name it as "Davao City Fire Hydrants" under "Philippines"

reference: https://github.com/mapamore/events/issues/14#issuecomment-322297882

**Comment by govvin** [comment]
This is now a stale request, but, would like to explore how it's possible to use the POI-importer for similar use cases in the future.

**Comment by obtitus** [comment]
Hi govvin, sorry for the late response, but this project is not actively maintained. To add a dataset you should also make a dataset.json file, example: https://github.com/POI-Importer/belgium-haltes-de-lijn/blob/1e91cf4b5839886f696883a0ee5e0a3923b90d56/dataset.json

See the readme for more details. The most efficient way of getting something added is with a pull-request.

**Comment by govvin** [comment]
I'll keep that in mind,  for next time Thank you @obtitus
