### ISSUE TITLE
Kindergartens in Norway

### ISSUE THREAD

**Issue by obtitus** [POI-Importer/POI-Importer.github.io#5]
Hi, does this look good:
http://obtitus.github.io/barnehagefakta_osm_data/POI-Importer-data/dataset.json ?
There is some information about the data here:
https://wiki.openstreetmap.org/wiki/Key:no-barnehage:nsrid
(I have sent an email to imports@openstreetmap.org, but it is stuck waiting for a moderator approval.)

Could you consider adding it if appropriate? 

Is there a simple way to run your tool locally for testing? I have yet to figure out whats up and down, and javascript is not my native language..

**Comment by obtitus** [comment]
I was able to get this running, please add somewhere prominent:
- Start JOSM
- In JOSM, ensure "Enable remote control" is enabled by going to "Preferences" -> "Settings for the remote control feature.".

I modified the loadData.js to:
var datasets = { 
"Norway" : {  
        "barnehagefakta":  
        {  
            "url": "http://obtitus.github.io/barnehagefakta_osm_data/POI-Importer-data/dataset.json",  
            "name": "Barnehagefakta fra Utdanningsdirektoratet",  
        }  
    }
};

And i enabled:
var types = ["node","way","rel"];
which seems to at least recognise kindergartens mapped as ways, but the "import" function just places a duplicate node. Relations does not seem to be picked up, could you see if this is fixable?
I have an example relation here: http://www.openstreetmap.org/relation/5462669

**Comment by sanderd17** [comment]
Sorry for the delay. For some reason, this github notification arrived in my non-important mailbox, so I saw your message to the imports list first :/

Different data types indeed aren't supported yet (though I planned support, and it won't be hard to add). But just to be clear. It won't import other data types, it will just recognise them when they are present in the OSM database. It will always import a point in JOSM, so you can copy the tags more easily (I can't predict how a feature will look from a POI database).

But thanks for the dataset, I'll look into including it.

**Comment by sanderd17** [comment]
I added the dataset to the tool, but I wonder if all those keys are needed.

Is the id useful for something? In the case of De Lijn, we can cunstruct an URL from the ref, and see the real-time bus info for that stop, so the ref is useful. Do you have something similar for kindergarten things? If no, the id doesn't belong in OSM IMO (so you should remove it from the tagmatch, but not from the database itself).

I also wonder if start_date is useful.

**Comment by obtitus** [comment]
In terms of supporting ways/relations. If the tags from the import node could be copied onto the OSM way/relation, (leaving the existing tags alone), then that would be sufficient. Is that implantation wise-impossible? I am not to familiar with the JOSM interface, but instead of sending a node, can you send a way/relation?

Hi, could we keep the tag discussion to the import list? As described here: 
http://wiki.openstreetmap.org/wiki/Key:no-barnehage:nsrid
the ref is being used by an automatic tool to keep the data up-to-date. It can also be used in various urls.

To be honest, I have no idea what the start_date might be useful for, but I figure I would include it anyway... In terms of mapping it, it is nice to know if it is completely new or ~30 years old.

**Comment by sanderd17** [comment]
Ok, I see that you can call a website using the ID, that's a nice feature, and for me enough to include it (it would be nice if you add it to openLinkMap too, like our bus stops: http://www.openlinkmap.org/?lat=50.94238&lon=3.0755&zoom=17&id=710108999&type=node )

Meanwhile, I altered the process to add data a bit, and the tool to split the files. It should be easier now. I gave you access to this repo: https://github.com/POI-Importer/norge-barnehagefakta , so you should be able to check out the project (as described here: https://github.com/POI-Importer/POI-Importer.github.io/blob/master/README.md , add the data like you had, and push it all again).

It should be more future proof, as from now on, I will be able to also alter your data (like when the parameters in the settings change).

**Comment by obtitus** [comment]
I might look into openlinkmap at some point. Is there a way to tell openlinkmap that the id should expand to a url? Or do I need another website= related tag?

Thanks, for the command line options, though I would recommend a nicer error message if one forgets to specify them.

Thank you, I have generated the data again (with the latest version) and pushed it to the new repository.

**Comment by sanderd17** [comment]
You can just tell the OpenLinkMap devs what the URL schema is, I don't know the exact procedure (Jo, aka Polyglot did it for the bus stops), but I imagine it's just filling an issue.

About the error messages, what message did you get?

**Comment by obtitus** [comment]
Running without giving the arguments returns:

> node tile_geojson.js
> POI-Importer.github.io/tile_geojson.js:15
> if (repo.charAt(repo.length - 1) != "/")
>         ^
> TypeError: Cannot read property 'charAt' of undefined

instead of a helpful usage print. (not a big issue!)

**Comment by sanderd17** [comment]
Guess the kindergartens are fine now, and I also added error messages to the tile_geojson script.

If you have any other, remaining issues, please open a new ticket ;)
