### ISSUE TITLE
Improve JOSM support

### ISSUE THREAD

**Issue by sanderd17** [POI-Importer/POI-Importer.github.io#7]
Apparently, remote-control isn't enabled by default (or not completely), so we should tell people why some click fails.

**Comment by sabas** [comment]
When the request fails, check also
if status == 0 -> josm not running or remote control not enabled
if status == 400 -> bad request, something got wrong with the call

**Comment by sanderd17** [comment]
Allowing to copy-paste tags would also be nice, apparently JOSM accepts JSON objects on the clipboard: https://josm.openstreetmap.de/ticket/8384

It shouldn't be hard to copy a JSON to the clipboard

**Comment by sabas** [comment]
You can paste tags in JOSM from a text formatted as this

```
amenity=fuel
name=Fuel station
```

**Comment by sanderd17** [comment]
I guess JSON is safer. What if some data in the dataset suddenly contains a strange character (like =)? JSON is standardised completely, and also very easy to generate from JS.

**Comment by obtitus** [comment]
I agree with sabas, copying plain text key=value is sufficient.
